# NeON Build File (https://github.com/c4s4/neon)

extends:
- c4s4/build/python.yml

properties:
  NAME:         'mail1'
  REQUIREMENTS: 'etc/requirements.txt'

targets:

  package:
    doc: Generate package
    depends: [clean]
    steps:
    - mkdir: =BUILD_DIR
    - copy:  'setup.py'
      dir:   'etc'
      todir: =BUILD_DIR
    - replace: '={BUILD_DIR}/setup.py'
      with:
        VERSION: =VERSION
    - $: ['pandoc', '-f', 'markdown', '-t', 'rst', 'README.md', '-o', '={BUILD_DIR}/README.rst']
    - copy:  ['LICENSE.txt', '={NAME}/**/*']
      todir: =BUILD_DIR
    - copy:  'MANIFEST.in'
      dir:   'etc'
      todir: =BUILD_DIR
    - chdir: =BUILD_DIR
    - $: ['../={VENV_DIR}/bin/python', 'setup.py', 'sdist', '-d', '.']

  upload:
    doc: Upload package
    depends: package
    steps:
    - chdir: =BUILD_DIR
    - $: ['../={VENV_DIR}/bin/python', 'setup.py','sdist', '-d', '.', 'upload']

  release:
    doc: Perform a release
    depends: [clean, test, upload]
    steps:
    - super:
